name: app-books
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - requests
  - python-dotenv
  - numpy
  - pillow
  - pyzbar
  - pip:
      - customtkinter
      - opencv-python